version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    env_file:
      - .env
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
    volumes:
      - minio_data:/data

  minio-init:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    env_file:
      - .env
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...' &&
      sleep 5 &&
      /usr/bin/mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      /usr/bin/mc mb -p local/${MINIO_BUCKET} || true &&
      /usr/bin/mc admin user add local ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} || true &&
      /usr/bin/mc admin policy attach local readwrite --user ${MINIO_ACCESS_KEY} &&
      echo 'MinIO initialized' &&
      exit 0;
      "

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - './monitoring_config/prometheus.yml:/etc/prometheus/prometheus.yml'
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/data

volumes:
  postgres_data:
  minio_data:
  prometheus_data:
  grafana_data:
  loki_data: