export const SECRET_PORT = Symbol("SECRET_PORT")
export const STORAGE_PORT = Symbol("STORAGE_PORT")


export const MOVIE_GENRE_REPOSITORY = Symbol("MOVIE_GENRE_REPOSITORY")
export const MOVIE_GENRE_SERVICE = Symbol("MOVIE_GENRE_SERVICE")

export const PROJECTION_TYPE_REPOSITORY = Symbol("PROJECTION_TYPE_REPOSITORY")
export const PROJECTION_TYPE_SERVICE = Symbol("PROJECTION_TYPE_SERVICE")

export const ROOM_SERVICE = Symbol("ROOM_SERVICE")
export const ROOM_REPOSITORY = Symbol("ROOM_REPOSITORY")

export const ROOM_IMAGE_SERVICE = Symbol("ROOM_IMAGE_SERVICE")
export const ROOM_IMAGE_REPOSITORY = Symbol("ROOM_IMAGE_REPOSITORY")

export const AUTH_SERVICE = Symbol("AUTH_SERVICE")
export const USER_SERVICE = Symbol("USER_SERVICE")
export const EMPLOYEE_SERVICE = Symbol("EMPLOYEE_SERVICE")

export const USER_REPOSITORY = Symbol("USER_REPOSITORY")
export const REFRESH_TOKEN_REPOSITORY = Symbol("REFRESH_TOKEN_REPOSITORY")
export const EMPLOYEE_REPOSITORY = Symbol("EMPLOYEE_REPOSITORY")
export const EMPLOYEE_SCHEDULE_REPOSITORY = Symbol("EMPLOYEE_SCHEDULE_REPOSITORY")