export const SECRET_PORT = Symbol("SECRET_PORT")
export const STORAGE_PORT = Symbol("STORAGE_PORT")


export const MOVIE_GENRE_REPOSITORY = Symbol("MOVIE_GENRE_REPOSITORY")
export const MOVIE_GENRE_SERVICE = Symbol("MOVIE_GENRE_SERVICE")

export const PROJECTION_TYPE_REPOSITORY = Symbol("PROJECTION_TYPE_REPOSITORY")
export const PROJECTION_TYPE_SERVICE = Symbol("PROJECTION_TYPE_SERVICE")
